### PR TITLE
Issue 4 ci

### PR DESCRIPTION
**Pull request by EricCrosson**
Examine this one closely -- your two commits on there may be fragments of the earlier rebase

Got the best way to remove them, if we must?

Edit: nvm I took care of it

### CODE REVIEW

**Comment by hershal** [comment]
That error is related to vectorization vs. naive implementations. Maybe Travis's CPU isn't capable of vectorization?

**Comment by EricCrosson** [comment]
It's just slower. I have run into these on my laptop even

**Comment by EricCrosson** [comment]
Applying solution, wait for this one to build...

**Review by EricCrosson — COMMENTED** [review]
Haven't used this function before

**Review by hershal — CHANGES_REQUESTED** [review]
Would be nice to see the time (maybe with a warning) if the test fails. We can do this in another branch.


I'm also curious as to why numpy can't vectorize on Travis's machines... but that's a discussion for a later time.

**Review by hershal — APPROVED** [review]

**Pull request merged**
