### PR TITLE
Feature/softmax classifier

### PR DESCRIPTION
**Pull request by hershal**
Reference issue #1. These tests look pretty nasty though. Any ideas on how to clean them up? I have two concerns: general test structure and the gradient check. My concern about the test structure is that it's almost entirely duplicated code. I suppose a better approach would be to create a test class which contains the duplicated behaviors, and supply the data in the constructor for testing. I'm not sure if this will act like mocha, which allows defining a test at runtime, so we'd have to experiment. My concern with the gradient check is that I'd like to generalize it, but I'm not sure how I would do so. Ideally the gradient check would work on any function which returns a tuple of a (scalar or vector) number and a gradient. I don't know where to start with that. Maybe properly implementing the gradient in the `LayerFullyConnected` would be a start.

Any tips?

### CODE REVIEW

**Comment by hershal** [comment]
These tests look pretty nasty though. Have any ideas on how to clean them up?

**Comment by EricCrosson** [comment]
I suppose a better approach would be to create a test class which contains the duplicated
    behaviors, and supply the data in the constructor for testing. I'm not sure if this will act
    like mocha, which allows defining a test at runtime, so we'd have to experiment.

Run-time is the only time for interpreted languages.  Subclassing our own base-class in `unittest.TestCase`'s stead will do exactly what you want.

Hopefully we can write some client code to the effect of

```
class TestClassifierSoftmaxDirected0(classifier.BaseTestCase):
    def setUp(self):
        # All three lines are always different -- not much room for savings
        self.scores = np.array([[3.2], [5.1], [-1.7]])
        self.train_labels = np.array([0])
        self.classifier = ClassifierSoftmax(self.scores.shape)

    def testSoftmaxLossNaive(self):
        classifier(self.classifier.softmax_loss_naive).should_have_loss(2.04035515)

    def testSoftmaxLossVectorized(self):
        classifier(self.classifier.softmax_loss_vectorized).should_have_loss(2.04035515)
```

(rspec is rubbing off on me)

**Review by EricCrosson — APPROVED** [review]
Functional for now, more abstracted design work is in place already. LGTM 👍

**Comment by EricCrosson** [comment]
You can open an issue if you want me to take care of this soon.  Otherwise, looks great let's keep up momentum, tackling red tests instead of already-green ones

**Comment by hershal** [comment]
Sounds good! I'll file an issue to track the cleanup (and put it in a cleanup milestone).

**Pull request merged**
